// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type S3 struct {
	ID               uuid.UUID
	Bucket           string
	Tags             string
	BucketDomainName string
	CreatedAt        time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Password  string
	ApiKey    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
