// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: s3.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createS3 = `-- name: CreateS3 :one
INSERT INTO s3 (id, bucket, tags, bucket_domain_name, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bucket, tags, bucket_domain_name, created_at
`

type CreateS3Params struct {
	ID               uuid.UUID
	Bucket           string
	Tags             string
	BucketDomainName string
	CreatedAt        time.Time
}

func (q *Queries) CreateS3(ctx context.Context, arg CreateS3Params) (S3, error) {
	row := q.db.QueryRowContext(ctx, createS3,
		arg.ID,
		arg.Bucket,
		arg.Tags,
		arg.BucketDomainName,
		arg.CreatedAt,
	)
	var i S3
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.Tags,
		&i.BucketDomainName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteS3 = `-- name: DeleteS3 :exec
DELETE FROM s3
WHERE bucket = $1
`

func (q *Queries) DeleteS3(ctx context.Context, bucket string) error {
	_, err := q.db.ExecContext(ctx, deleteS3, bucket)
	return err
}
